#!/bin/bash

# load the us layout

nitrogen --head=0 --set-zoom-fill ~/Pictures/Wallpaper/0146.jpg
nitrogen --head=1 --set-zoom-fill ~/Pictures/Wallpaper/0146.jpg
betterlockscreen -u ~/Pictures/Wallpaper/0146.jpg &
dunstify -u low -r 10 "Changed to docked monitor layout" 
xset r rate 200 30 &
