#!/bin/bash

setxkbmap us
xmodmap ~/.Xmodmap
nitrogen --head=0 --set-zoom-fill ~/Pictures/Wallpaper/0146.jpg
nitrogen --head=1 --set-zoom-fill ~/Pictures/Wallpaper/0146.jpg
betterlockscreen -u ~/Pictures/Wallpaper/0146.jpg &
