#!/bin/bash

setxkbmap us
xmodmap ~/.Xmodmap
nitrogen --head=0 --set-zoom-fill /usr/share/backgrounds/druhwald.JPG
nitrogen --head=1 --set-zoom-fill /usr/share/backgrounds/druhwald.JPG
multilockscreen -u ~/Pictures/druhwald.JPG
